---

- hosts: all

  tasks:
          - name: Using template, create a remote file that contains all vars
            template:
                    src: templates/dump_variables
                    dest: /tmp/ansible_variables


          - name: Fetch the templated file with all variables
            fetch:
                    src: /tmp/ansible_variables
                    dest: "captured_variables/{{ ansible_hostname }}"
                    flat: yes

                    #        - name: clean up left overs
                    #  file:
                    #   name: /tmp/ansible_variables
                    #  state: absent
