---

- hosts: all

  tasks:
          - name: Using template, create a remote file that contains all vars
            template:
                    src: templates/dump_hostname
                    dest: /tmp/ansible_hostname


          - name: Fetch the templated file with all variables
            fetch:
                    src: /tmp/ansible_hostname
                    dest: "captured_hostname/{{ ansible_hostname }}"
                    flat: yes

          - name: clean up left overs
            file:
                    name: /tmp/ansible_hostname
                    state: absent
