---
# tasks file for nginx---

  - name: Install Epel
    yum:
            name: epel-release
            update_cache: yes
            state: latest
    when: ansible_distribution == 'CentOS'

  - name: Install Nginx
    package:
            name: nginx
            state: latest
  - name: Install Patch
    yum:
            name: patch
            update_cache: yes
            state: latest
    when: ansible_distribution == 'CentOS'

  - name: Patch nginx.conf to include site-available, disable default server entry
    patch:
            src: files/nginx.conf.centos.patch
            dest: /etc/nginx/nginx.conf
    when: ansible_distribution == 'CentOS'

  - name: Create directory /etc/nginx/sites-available
    file:
            path: /etc/nginx/sites-available
            state: directory
  
  - name: Create /etc/nginx/sites-enabled directory
    file:
            path: /etc/nginx/sites-enabled
            state: directory
  
  - name: Copy default nginx configuration
    copy:
            src: files/nginx-default.conf
            dest: /etc/nginx/sites-available/default
  
  - name: Symbolic link
    file:
            src: /etc/nginx/sites-available/default
            dest: /etc/nginx/sites-enabled/default
            state: link
  
  - name: Create nginx/html directory
    file: 
        path: /usr/share/nginx/html
        state: directory
  
  - name: Template index.html.j2 to index.html on target
    template:
            src: templates/index.html.j2
            dest: /usr/share/nginx/html/index.html
            mode: 0644

  - name: Restart nginx
    service:
            name: nginx
            state: restarted
    notify: Check HTTP Service

  - name: Open Centos firewall for Nginx
    firewalld:
            service: http
            permanent: true
            state: enabled
    when: ansible_distribution == 'CentOS'
    notify: Reload firewall

  - name: enable nginx
    service:
            name: nginx
            enabled: yes



...
