---

- hosts: linux
  tasks:
        - name: Task 1
          command: /bin/sleep 5
          when: ansible_hostname == 'centos1'

        - name: Task 2
          command: /bin/sleep 5
          when: ansible_hostname == 'centos2'

        - name: Task 3
          command: /bin/sleep 5
          when: ansible_hostname == 'centos3'

        - name: Task 4
          command: /bin/sleep 5
          when: ansible_hostname == 'ubuntu1'

        - name: Task 5
          command: /bin/sleep 5
          when: ansible_hostname == 'ubuntu2'

        - name: Task 6
          command: /bin/sleep 5
          when: ansible_hostname == 'ubuntu3'

...

