---

- hosts: linux
  tasks:
        - name: Task 1
          command: /bin/sleep 5
          when: ansible_hostname == 'centos1'
          async: 10
          poll: 0
          register: result1

        - name: Task 2
          command: /bin/sleep 5
          when: ansible_hostname == 'centos2'
          async: 10
          poll: 0
          register: result2

        - name: Task 3
          command: /bin/sleep 5
          when: ansible_hostname == 'centos3'
          async: 10
          poll: 0
          register: result3

        - name: Task 4
          command: /bin/sleep 30
          when: ansible_hostname == 'ubuntu1'
          async: 10
          poll: 0
          register: result4

        - name: Task 5
          command: /bin/sleep 5
          when: ansible_hostname == 'ubuntu2'
          async: 10
          poll: 0
          register: result5

        - name: Task 6
          command: /bin/sleep 5
          when: ansible_hostname == 'ubuntu3'
          async: 10
          poll: 0
          register: result6


...

