---

- hosts: linux


  tasks:
          - name: creating user
            user:
                    name: "{{ item.key }}"
                    comment: "{{ item.value.full_name }}"
            with_dict:
                    james:
                            full_name: James Sp

          - name: Create sequence directories
            file:
                    dest: "{{ item }}"
                    state: directory
            with_sequence: start=0 end=16 stride=1 format=/home/james/hex_sequence_%x
