---

- hosts: linux


  tasks:
          - name: creating user
            user:
                    name: "{{ item.key }}"
                    comment: "{{ item.value.full_name }}"
            with_dict:
                    james:
                            full_name: James Sp

          - name: creating authorized key
            authorized_key:
                     user: james
                     key: "{{ item }}"
            with_file:
                     - /home/vagrant/.ssh/id_rsa.pub
