---

- hosts: all

  tasks:
          - name: Ansible jinja2 if elif
            debug:
                    msg: > 
                            --== Ansible jinja2 if elif statement ==--

                            {% if ansible_hostname == "ubuntuc" -%}
                                This is ubuntuc
                            {% elif ansible_hostname == "centos1" -%}
                                This is centos1 with port 2222
                            {% endif %}
...

