---

- hosts: all

  tasks:
          - name: Ansible jinja2 filters
            debug:
                    msg: >
                            --== Ansible jinja2 filters ==--
                             {{ [1, 2, 3, 4, 5] | min }}
                             {{ [1, 2, 3, 4, 5] | max }}
                             {{ [1, 3, 4, 4, 3, 5, 5] | unique }}
                             {{ [1, 2, 3, 4, 5] | difference([2, 3, 5]) }}
                             {{ ['rob', 'mike', 'sam' ] | random }}
                             {{ "https://docs.ansible.com/ansible/2.5/user_guide/playbooks_filters.html" | urlsplit('hostname') }} 
                           
