---

- hosts: all

  tasks:
          - name: Ansible jinja2 for reverse range with if statement continue
            debug:
                    msg: >
                            --== Ansible jinja2 for range

                            {% for entry in range(10, 0, -1) -%}
                                {% if entry is odd -%}
                                        {% continue %}
                                {% endif -%}   
                                {{ entry }}
                            {% endfor %}
...
