---

- hosts: linux

  tasks:
          - name: Exploring register
            command: hostname -s
            register: hostname_output

          - name: show the output
            debug:
                    var: hostname_output
...
