---

- hosts: linux

  tasks:
          - name: Exploring register
            command: hostname -s
            when: ( ansible_distribution == "CentOS" and ansible_distribution_major_version | int >= 6 ) or 
                  ( ansible_distribution == "Ubuntu" and ansible_distribution_major_version | int >= 16 ) 
        
...
